# References

Bhanumathi, P., Basu, S., & Babu, B. S. (2024). Artificial intelligence and machine learning- powered recruitment for smart hiring. In Global Practices on Effective Talent Acquisition and Retention (pp. 17–36). https://doi.org/10.4018/979-8-3693-1938-3.ch002

Born, M. P., Taris, T. W., & Willemsen, T. M. (2010). “Perceptions of gender-focused or gender-neutral job advertisements: The effects of job characteristics, communal requirement, and sex of the applicant.” European Journal of Work and Organizational Psychology, 18(3), 279–305. https://doi.org/10.1080/00224540903365422 

Doughman, J., & Khreich, W. (2022). Gender bias in text: Labeled datasets and lexicons. ArXiv, abs/2201.08675.

Frissen, R., Adebayo, K. J., & Nanda, R. (2023). A machine learning approach to recognize bias and discrimination in job advertisements. AI & Society, 38, 1025–1038. https://doi.org/10.1007/s00146-022-01574-0

Gaucher, D., Friesen, J., & Kay, A. C. (2011). Evidence that gendered wording in job advertisements exists and sustains gender inequality. Journal of Personality and Social Psychology, 101(1), 109–128. https://doi.org/10.1037/a0022530

Heilman, M. E. (2012) “Gender stereotypes and workplace bias.” Research in Organizational Behavior, 32, 113–135.https://doi.org/10.1016/j.riob.2012.11.003 

Kusner, M. J., Loftus, J. R., Russell, C., & Silva, R. (2017, March 20). Counterfactual fairness. In Advances in Neural Information Processing Systems, 2017-December (pp. 4067–4077). arXiv.org. https://arxiv.org/abs/1703.06856

Liu, H., Jin, W., Karimi, H., Liu, Z., & Tang, J. (2021). The Authors Matter: Understanding and Mitigating Implicit Bias in Deep Text Classification. Association for Computational Linguistics, 74–85. https://aclanthology.org/2021.findings-acl.7.pdf 

Mulkar-Mehta, R., Hobbs, J., & Hovy, E. (2011). Granularity in natural language discourse. In J. Bos & S. Pulman (Eds.), Proceedings of the Ninth International Conference on Computational Semantics (IWCS 2011). Association for Computational Linguistics. https://aclanthology.org/W11-0143

Rudman, L. A., & Glick, P. (2001). Prescriptive gender stereotypes and backlash toward agentic women. Journal of Social Issues, 57(4), 743–762. https://doi.org/10.1111/0022- 4537.00239

Schneider, B. (1987). The people make the place. Personnel Psychology, 40(3), 437–453. https://doi.org/10.1111/j.1744-6570.1987.tb00609.x

Smith, K., Davenport, B. L., Bickford, J. F., Abell, L., & Dooley, S. (2023). The effects of jargon in STEM job advertisements on genders. Paper presented at the 2023 ASEE Annual Conference & Exposition, Baltimore, Maryland. https://doi.org/10.18260/1-2--44447

Tambe, P., Cappelli, P., & Yakubovich, V. (2019). Artificial intelligence in human resources
management: Challenges and a path forward. California Management Review, 61(4), 15–42. https://doi.org/10.1177/0008125619867910

